apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-mutator-account
  labels:
    app: mutatepodtoleration.liqo.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-mutator-cluster-rolebinding
  labels:
    app: mutatepodtoleration.liqo.io
subjects:
  - kind: ServiceAccount
    name: pod-mutator-account
    namespace: liqo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-mutator-cluter-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: pod-mutator-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
      - update
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-mutator-secrets-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-mutator-secrets-rolebinding
  namespace: liqo
subjects:
  - kind: ServiceAccount
    name: pod-mutator-account
    namespace: liqo
roleRef:
  kind: Role
  name: pod-mutator-secrets-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: mutatepodtoleration
  labels:
    app: mutatepodtoleration.liqo.io
spec:
  selector:
    app: mutatepodtoleration.liqo.io
  ports:
    - port: 443
      targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podmutator
  labels:
    app: mutatepodtoleration.liqo.io
spec:
  selector:
    matchLabels:
      app: mutatepodtoleration.liqo.io
  template:
    metadata:
      labels:
        app: mutatepodtoleration.liqo.io
    spec:
      serviceAccountName: pod-mutator-account
      initContainers:
      - name: secret-creation
        image: liqo/secret-creation
        imagePullPolicy: Always
        args:
          - "--namespace"
          - liqo
          - "--service"
          - "mutatepodtoleration"
          - "--secret"
          - "pod-mutator-secret"
          - "--export-env-vars"
          - "--output-env-file"
          - "/etc/environment/liqo/env"
          - "--output-dir"
          - "/etc/ssl/liqo"
        volumeMounts:
          - mountPath: /etc/ssl/liqo
            name: certs-volume
          - mountPath: /etc/environment/liqo
            name: env-volume
        resources:
          limits:
            cpu: 100m
            memory: 100M
          requests:
            cpu: 100m
            memory: 100M
      - name: pod-mutator-deployment
        image: liqo/init-pod-mutator
        imagePullPolicy: Always
        args:
          - "--input-env-file"
          - "/etc/environment/liqo/env"
        volumeMounts:
          - mountPath: /etc/environment/liqo
            name: env-volume
        resources:
          limits:
            cpu: 100m
            memory: 50M
          requests:
            cpu: 100m
            memory: 50M
      containers:
      - name: podmutator
        image: liqo/pod-mutator
        imagePullPolicy: Always
        args:
          - "--input-env-file"
          - "/etc/environment/liqo/env"
        volumeMounts:
        - mountPath: /etc/ssl/liqo
          name: certs-volume
        - mountPath: /etc/environment/liqo
          name: env-volume
        resources:
          limits:
            cpu: 100m
            memory: 50M
          requests:
            cpu: 100m
            memory: 50M
      volumes:
        - name: certs-volume
          emptyDir: {}
        - name: env-volume
          emptyDir: {}
