apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.podMutatorServiceName }}
  labels:
    app: liqo.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.global.podMutatorServiceName }}
  labels:
    app: liqo.io
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.podMutatorServiceName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.podMutatorServiceName }}
  labels:
    app: liqo.io
spec:
  selector:
    app: {{ .Values.global.podMutatorServiceName }}
  ports:
    - port: 443
      targetPort: 8443

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: podmutator
  labels:
    app: {{ .Values.global.podMutatorServiceName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.global.podMutatorServiceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.podMutatorServiceName }}
    spec:
      serviceAccountName: {{ .Values.global.podMutatorServiceName }}
      containers:
        - name: {{ .Values.global.podMutatorServiceName }}
          image: {{ .Values.mutatingWebhook.image.repository }}{{ .Values.global.suffix | default .Values.suffix }}:{{ .Values.global.version | default .Values.version }}
          imagePullPolicy: Always
          args:
            - "--input-env-file"
            - "/etc/environment/liqo/env"
          volumeMounts:
            - mountPath: /etc/ssl/liqo
              name: certs-volume
            - mountPath: /etc/environment/liqo
              name: env-volume
          resources:
            limits:
              cpu: 100m
              memory: 50M
            requests:
              cpu: 100m
              memory: 50M
      volumes:
        - name: certs-volume
          secret:
            secretName: {{ .Values.global.podMutatorSecretName }}
        - name: env-volume
          emptyDir: {}