# Default values for crdreplicator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: liqo/crd-replicator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.

suffix: ""
version: "latest"