# Default values for liqo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##### Needed
suffix: ""
version: "latest"

#configuration values for the adv subchart
advertisementOperator:
  advController:
    image:
      repository: "liqo/advertisement-operator"
      pullPolicy: "IfNotPresent"
  broadcaster:
    image:
      repository: "liqo/advertisement-broadcaster"
      pullPolicy: "IfNotPresent"
  enabled: true

#configuration values for the networkModule subchart
networkModule:
  routeOperator:
    image:
      repository: "liqo/liqonet"
      pullPolicy: "IfNotPresent"
  tunnelEndpointOperator:
    image:
      repository: "liqo/liqonet"
      pullPolicy: "IfNotPresent"
  enabled: true

#configuration values for the tunnelendpointCreator subchart
tunnelEndpointCreator:
  image:
    repository: "liqo/liqonet"
    pullPolicy: "IfNotPresent"
  enabled: true

#configuration values for the schedulingNode subchart
schedulingNodeOperator:
  image:
    repository: "liqo/scheduling-node-operator"
    pullPolicy: "IfNotPresent"
  enabled: true

webhooksInstaller:
  image:
    repository: "mlvc/pm"
    pullPolicy: "IfNotPresent"
  enabled: true

#configuration values for the mutatingWebhook subchart
mutatingWebhook:
  image:
    repository: "liqo/pod-mutator"
    pullPolicy: "IfNotPresent"
  enabled: true

discoveryOperator:
  image:
    repository: "liqo/discovery"
    pullPolicy: "IfNotPresent"
  apiServerIp: ""
  apiServerPort: ""
  enabled: true

peeringRequestOperator:
  image:
    repository: "liqo/peering-request-operator"
    pullPolicy: "IfNotPresent"
  serviceName: peering-request-operator
  secretName: peering-request-webhook-certs
  enabled: true

liqodash:
  image:
    repository: "liqo/dashboard"
    pullPolicy: "IfNotPresent"
  enabled: true

crdReplicator:
  image:
    repository: "liqo/crdreplicator"
    pullPolicy: "IfNotPresent"
  enabled: true

global:
  configmapName: "liqo-configmap"
  dashboard_ingress: ""
  dashboard_version: ""
  podMutatorServiceName: pod-mutator
  podMutatorSecretName: pod-mutator-certs
  peeringRequestOperatorServiceName: peering-request-operator
  peeringRequestOperatorSecretName: peering-request-operator-certs
  suffix: ""
  version: ""
