name: Integration Pipeline
on:
  push:
    tags:
      - 'v*'
    branches:
      - master
  pull_request:
jobs:
  configure:
    name: Preliminary configuration
    runs-on: ubuntu-latest
    outputs:
      commit_ref: ${{ steps.configure.outputs.commit_ref }}
      repo-suffix: ${{ steps.configure.outputs.repo-suffix }}
      repo-push: ${{ steps.configure.outputs.repo-push }}
      master: ${{ steps.configure.outputs.master }}
    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      if: startsWith(github.ref, 'refs/tags/v')
    - name: Configure
      id: configure
      run: |
        # The ref of the commit to checkout (do not use the merge commit if pull request)
        if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
          echo "::set-output name=master::false"
          echo "::set-output name=commit_ref::${{ github.event.pull_request.head.sha }}"
        elif [ "${{ steps.get_version.outputs.VERSION }}" != "" ]; then
          echo "::set-output name=master::false"
          echo "::set-output name=commit_ref::${{ steps.get_version.outputs.VERSION }}"
        else
          echo "::set-output name=master::true"
          echo "::set-output name=commit_ref::${{ github.sha }}"
        fi

        # The suffix to append to the repository name if not triggered by a push to master
        [[ "${{ steps.get_version.outputs.VERSION }}" == "" ]] && \
          echo "::set-output name=repo-suffix::-ci" ||
          echo "::set-output name=repo-suffix::"

        # Do not push the resulting images to DockerHub if triggered by a fork
        [[  "${{ github.event.repository.full_name }}" != 'liqotech/liqo' ]] && \
            echo "::set-output name=repo-push::false" || \
            echo "::set-output name=repo-push::true"

  build:
    runs-on: ubuntu-latest
    needs: configure
    strategy:
      fail-fast: false
      matrix:
        component:
        - virtual-kubelet
        - liqonet
        - advertisement-broadcaster
        - advertisement-operator
        - init-vkubelet
        - scheduling-node-operator
        - discovery
        - peering-request-operator
        - secret-creation
        - init-pod-mutator
        - pod-mutator
        - peering-request-webhook-init
        - crd-replicator
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: "${{ needs.configure.outputs.commit_ref }}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: needs.configure.outputs.repo-push == 'true'

      - name: Build (and Publish) ${{ matrix.component }} image
        uses: docker/build-push-action@v2
        with:
          tags: |
            liqo/${{ matrix.component }}${{ needs.configure.outputs.repo-suffix }}:latest
            liqo/${{ matrix.component }}${{ needs.configure.outputs.repo-suffix }}:${{ needs.configure.outputs.commit_ref }}
          push: ${{ needs.configure.outputs.repo-push }}
          file: build/${{ matrix.component }}/Dockerfile

  e2e-test-trigger:
     runs-on: ubuntu-latest
     needs: [build, configure]
     if: needs.configure.outputs.repo-push == 'true' && github.event.pull_request.draft == false
     strategy:
       fail-fast: false
       matrix:
         component:
         - liqops
         - doc-website
     steps:
       - uses: actions/checkout@v2
         with:
           ref: "${{ env.commit_ref }}"
       - name: Notify Event to ${{ matrix.component }}
         uses: peter-evans/repository-dispatch@v1
         with:
           token: ${{ secrets.CI_TOKEN }}
           repository: liqotech/${{ matrix.component }}
           event-type: "dev-event"
           client-payload: |
             {
               "master": "${{ needs.configure.outputs.master }}",
               "commit": "${{ needs.configure.outputs.commit_ref }}"
             }

  release:
    runs-on: ubuntu-latest
    needs: [build, test, configure]
    if: github.event_name == 'push' && github.event.repository.full_name == 'liqotech/liqo' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # The changelog generation requires the entire history
          fetch-depth: 0
          persist-credentials: false

      - name: Get the Liqo version to be released
        id: version
        run: echo "version::${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Get the latest Liqo release
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        id: last-release
        with:
          repository: ${{ github.repository }}

      - name: Generate the CHANGELOG
        uses: RiskLedger/generate-changelog@v1.2
        id: changelog
        with:
          from: ${{ steps.last-release.outputs.release }}
          to: ${{ needs.configure.outputs.commit_ref }}
        env:
          GITHUB_AUTH: ${{ secrets.CI_TOKEN }}

      - name: Save the CHANGELOG as a file
        run: |
          echo "${{ steps.changelog.outputs.changelog }}" > ./CHANGELOG.md
          sed -i "1s/.*/## Changes since ${{ needs.configure.outputs.commit_ref }}/" ./CHANGELOG.md

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ needs.configure.outputs.commit_ref }}
          release_name: ${{ needs.configure.outputs.commit_ref }}
          body_path: ./CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}

# Agent Upload Artifact
      - name: Download Agent artifact
        uses: actions/download-artifact@v2
        with:
          name: agent_artifact

      - name: Upload Agent asset to release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: liqo-agent.tar.gz
          asset_content_type: application/gzip
          github_token: ${{ secrets.CI_TOKEN }}
          overwrite: true


  test:
    name: Launch Test and Build Liqo Agent
    runs-on: ubuntu-20.04
    needs: configure
    if: github.event.pull_request.draft == false
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        ref: "${{ needs.configure.outputs.commit_ref }}"

    - name: Install Kubebuilder
      run: |
        version=2.3.1 # latest stable version
        arch=amd64
        curl -L -O "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${version}/kubebuilder_${version}_linux_${arch}.tar.gz"
        tar -zxvf kubebuilder_${version}_linux_${arch}.tar.gz
        mv kubebuilder_${version}_linux_${arch} kubebuilder && sudo mv kubebuilder /usr/local/

    - name: Get dependencies for Test execution
      run: |
        go get -u github.com/ory/go-acc
        go get -u github.com/cratonica/2goarray

    - name: install tray-agent dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt update
        sudo apt-get -y install gcc libgtk-3-dev libappindicator3-dev libxapp-dev libwebkit2gtk-4.0-dev xclip

    - name: generate tray-agent icons
      run: |
        chmod +x ./scripts/tray-agent/make_icon.sh
        ./scripts/tray-agent/make_icon.sh

    - name: Launch Test
      run: go-acc ./... --ignore liqo/test/e2e

    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.txt

    - name: Build Agent asset
      run: |
        GO111MODULE=on CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build ./cmd/tray-agent/liqo-agent.go
        tar -czf liqo-agent.tar.gz liqo-agent
      if: github.event_name == 'push' && github.event.repository.full_name == 'liqotech/liqo' && startsWith(github.ref, 'refs/tags/v')

    - name: Upload Agent artifact
      uses: actions/upload-artifact@v2
      with:
        name: agent_artifact
        path: liqo-agent.tar.gz
        retention-days: 1
        if-no-files-found: error
      if: github.event_name == 'push' && github.event.repository.full_name == 'liqotech/liqo' && startsWith(github.ref, 'refs/tags/v')
